micronaut:
  application:
    name: webgame
  server:
    cors:
      enabled: true
#      configurations:
#        ui:
#          allowed-origins:
#            - http://127.0.0.1:8000
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    url: ${POSTGRES_URL:`jdbc:postgresql://127.0.0.1:5432/postgres`}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:changeme}

flyway:
  datasources:
    default:
      enabled: true

mailjet:
  enabled: false
  api-key: ${MAILJET_API_KEY}
  api-secret: ${MAILJET_API_SECRET}

app:
  site_url: 'http://localhost:8080/'
  register:
    code_expire: 5
    activate_path: '/activate'