micronaut:
  application:
    name: webgame
  server:
    cors:
      enabled: true
#      configurations:
#        ui:
#          allowed-origins:
#            - http://127.0.0.1:8000
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    url: ${POSTGRES_URL:`jdbc:postgresql://127.0.0.1:5432/postgres`}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:changeme}

flyway:
  datasources:
    default:
      enabled: true

mailjet:
  enabled: true
  api-key: '1a3ab893c9672918f7026172eabf07cf'
  api-secret: '0ccf4bd010443ae2b4939d5c5eb44eed'

app:
  site_url: 'http://localhost:8080'
  user:
    register:
      code_expire: 5
      path: '/activate'
    forgot_pass:
      code_expire: 5
      path: '/forgot-password'